language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "3.1"
script:
  - python ShiftRegister.py
  - python Encoder4b5b.py
  - python Decoder4b5b.py
  - python HardwareBlock.py
